### PR TITLE
Moving static from global scope for issue 898

### PR DESCRIPTION
**Pull request by v-makouz**

### CODE REVIEW

**Comment by keitherskine** [comment]
@mkleehammer This PR seems like a good candidate for a squash merge rather than a rebase merge.

**Comment by mkleehammer** [comment]
@v-chojas There are a bunch of commits on this, but I thought the last time I looked it was actually a pretty small change.  Can you squash and rebase onto master so I can test it?  Thanks.

**Comment by v-chojas** [comment]
@v-makouz could you look into this?

**Comment by v-makouz** [comment]
This should be a cleaner Pull Request: https://github.com/mkleehammer/pyodbc/pull/923

**Comment by gordthompson** [comment]
superseded by #923

**Pull request closed without merging**
