### PR TITLE
Run unit tests with AppVeyor CI

### PR DESCRIPTION
**Pull request by keitherskine**
Note, this PR has a dependency on PR #705 .

This PR is an attempt to introduce automated building and testing of pyodbc commits (on Windows), across a range of Python versions and databases.  With this update, AppVeyor CI will run the existing unit tests on Windows AppVeyor servers for the following databases and ODBC drivers:

- MS SQL Server 2017
  - {SQL Server Native Client 10.0} (if available on the server)
  - {SQL Server Native Client 11.0} (if available on the server)
  - {ODBC Driver 11 for SQL Server}
  - {ODBC Driver 13 for SQL Server}
  - {ODBC Driver 17 for SQL Server} 
- PostgreSQL 11
  - {PostgreSQL Unicode} (32-bit Python)
  - {PostgreSQL Unicode(x64)} (64-bit Python)
- MySQL 5.7
  - {MySQL ODBC 5.3 ANSI Driver} (Python 2.7)
  - {MySQL ODBC 8.0 ANSI Driver} (Python 3)

The existing unit tests will be run against Python versions 2.7, 3.5, 3.6, 3.7, and 3.8.

Most of the functionality is accomplished through DOS/Powershell batch scripts.  The main one is the DOS script that runs the tests (`appveyor\test_script.cmd`).  It's MS-DOS so is kinda long-winded and clunky but it does the job.  Building the pyodbc module, especially for Python 2.7, is facilitated using a script (`appveyor\compile.cmd`) created by Olivier Grisel.  I'm no expert on compiling C++ in a Windows environment so I'll be happy and grateful for any feedback on this approach.

There are various environmental variables that can be set to control which databases are tested and whether "wheel" distributable files are generated.  See the `appveyor.yml` file for details.  Wheel files are made available as AppVeyor artifacts, downloadable through the AppVeyor UI.  You will need to [sign up](https://ci.appveyor.com/signup) for an AppVeyor account for this, and probably fork the pyodbc repo too.

Some ODBC drivers are pre-installed in the AppVeyor VM images.  Some need to be installed at the start of each job.  These drivers are downloaded from their source if necessary, but to make the CI process quicker and more reliable, the AppVeyor [cache](https://www.appveyor.com/docs/build-cache/) mechanism is used to store the msi files between builds.

There are four AppVeyor Windows VM images - "Visual Studio 2013", "Visual Studio 2015", "Visual Studio 2017", and "Visual Studio 2019".  Each image has a different combination of [databases](https://www.appveyor.com/docs/services-databases/) and [other software](https://www.appveyor.com/docs/windows-images-software/) pre-installed on it.  Note, each major version of Python can be compiled with only some versions of Visual Studio.  So, it's been an exercise in finding the right combination of Visual Studio and databases to enable all versions of Python to be built and tested.  For example, on the "Visual Studio 2019" image, only SQL Server 2017 is available.  I would have liked to test against other versions of SQL Server, but the Python wheel files now being published to PyPi are being compiled against Visual Studio 2019 (since Dec 2019), so SQL Server 2017 is all that is immediately available.  It's possible to install other RDBMS's into the AppVeyor VM images during each build, but that will slow down the jobs considerably so I've avoided doing that so far.  Perhaps that can be addressed later on.  It may also be possible to get AppVeyor themselves to install more versions of SQL Server on the "Visual Studio 2019" image, they seem to be receptive to requests.

FYI, I haven't tested the wheel files that are generated by this CI process.  They should be downloaded and installed on a separate machine at some point to verify them.

Hopefully this PR will provide a mechanism for automatically testing all new updates to pyodbc (on Windows anyway).  Only three databases are tested at the moment, but maybe that can be improved over time.

Any and all thoughts welcome.

### CODE REVIEW

**Comment by keitherskine** [comment]
FYI @mkleehammer , I'm making some fairly significant changes to this at the moment (for the better), so please don't merge PR this yet.

**Comment by mkleehammer** [comment]
I did not realize there were databases available on AppVeyor.  This is killer!   I'm looking forward to this.

**Comment by keitherskine** [comment]
I believe this PR is now ready for review.

I note the build has actually failed on AppVeyor.  This seems to be because the MySQL driver could not be downloaded from the MySQL ftp site for one of the 12 jobs, and this seems to have happened before as well.  Bear in mind, the CI process has to wholly succeed just once and then the driver files will be stored in the AppVeyor cache.  @mkleehammer , could I ask you to manually re-run the failed job through the [AppVeyor UI](https://ci.appveyor.com/project/mkleehammer/pyodbc)?  (There should be a button on that "Current build" screen called "RE-RUN INCOMPLETE").  Many thanks.

**Comment by keitherskine** [comment]
By the way, the issue with the Python 3.5 build went away.  I believe this was because either Visual Studio 2019 was fixed or `setuptools.py` was fixed, or both.  Regardless, Python 3.5 can now be built without any issues.

**Comment by mkleehammer** [comment]
Your first comment says this depends on PR #705 which I added a question to.  Thanks.

**Comment by mkleehammer** [comment]
Oh thanks.  I wasn't actually asking you to do it - I was just trying to figure out the best way to fix the mere issues.

**Pull request merged**
