### PR TITLE
Fix for 596

### PR DESCRIPTION
**Pull request by v-makouz**
https://github.com/mkleehammer/pyodbc/issues/596

I tried this with the repro app, and ran the sqlserver tests, everything seems to work OK

### CODE REVIEW

**Comment by Zeddicus414ce** [comment]
I ran into #596 as well. I was glad to see that this is in work! Thank you.

I was using the test_tvp code to track down the problem before I found this ticket. Would adding a None/NULL input to the test_tvp be helpful here? Perhaps changing c05 to [1, 0, None]?

**Comment by eydelrivero** [comment]
Glad to see this has been fixed. Will this pull request be merged any time soon?

**Comment by githubuserkkk** [comment]
I still see the issue if we have None in the first row. ('HY004', '[HY004] [Microsoft][SQL Server Native Client 11.0]Invalid SQL data type (0) (SQLBindParameter)

**Comment by vikas-clinch** [comment]
I am also

> I still see the issue if we have None in the first row. ('HY004', '[HY004] [Microsoft][SQL Server Native Client 11.0]Invalid SQL data type (0) (SQLBindParameter)

Me too

**Comment by himanshu754** [comment]
> I still see the issue if we have None in the first row. ('HY004', '[HY004] [Microsoft][SQL Server Native Client 11.0]Invalid SQL data type (0) (SQLBindParameter)

I am also facing this issue

**Pull request merged**
