### PR TITLE
Fix for truncation error when inserting high unicode characters

### PR DESCRIPTION
**Pull request by v-makouz**

### CODE REVIEW

**Comment by srish13** [comment]
@mkleehammer  Because of this issue we are not able to support Unicode characters in our application.  Consider this fix as a high priority as this is blocking developers to use Unicode characters in their application.

**Comment by mkleehammer** [comment]
@v-makouz I realized I've been replying to the issue #423 instead of this PR.  Copying over some of the conversation:

Can we change it to look at the enc.optenc flag instead of enc.name? That way all of the code that looks for the different combinations that mean "utf-16" are in one place (SetTextEncCommon).

Also, can we add some unit tests for the 3 most common.

* PostgreSQL
* SQL Server
* MySQL
* Oracle - I've added this because I think it was mentioned you already had a test.  If not, don't worry about it.  It isn't easy to set up and test.

Here's the test I used for PostgreSQL, but it should work for all of them (it's on the 433-emoticons branch):

    def test_emoticons(self):
        # https://github.com/mkleehammer/pyodbc/issues/423
        #
        # When sending a varchar parameter, pyodbc is supposed to set ColumnSize to the number
        # of characters.  Ensure it works even with 4-byte characters.
        #
        # http://www.fileformat.info/info/unicode/char/1f31c/index.htm

        v = "x \U0001F31C z"

        self.cursor.execute("create table t1(s varchar(100))")
        self.cursor.execute("insert into t1 values (?)", v)

        result = self.cursor.execute("select s from t1").fetchone()[0]

        self.assertEqual(result, v)

**Comment by mkleehammer** [comment]
@v-makouz I pulled and tested and it looks great.  I don't want to steal your authorship and GitHub says it can't automatically rebase, so can you rebase it to a single commit and I'll merge it in?

**Comment by v-makouz** [comment]
@mkleehammer I've made the change to use enc.optenc and I've added the tests, as you said most work as is, but for Python3 version of SQL Server tests I had to replace varchar with nvarchar.

**Comment by v-makouz** [comment]
@mkleehammer I've squished my commits

**Comment by mkleehammer** [comment]
Cherry picked to 686d2b0 since there were other commits between master and it.

Thanks for this fix and the docs pointer.

Closes #434 and I believe #423

**Comment by srish13** [comment]
@mkleehammer When will next release will happen with this change.

**Comment by mkleehammer** [comment]
I will make a release today and include 3.7 binary wheels for Windows and macOS.

**Pull request closed without merging**
